name: Open URL on Successful Merge

on:
  pull_request:
    types:
      - closed

jobs:
  open-url:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        node-version: '20'  # Specify Node.js version

    - name: Open URL on successful merge
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        curl -L -f -S -s https://himo.toolforge.org/update.php?dump=1 > curl_output.txt || echo "Curl request failed with status code $?"
